start: expr

?expr: term
     | expr "+" term  -> add
     | expr "-" term  -> subtract

?term: factor
     | term "*" factor  -> multiply
     | term "/" factor  -> divide

?factor: NUMBER        -> number
       | "(" expr ")"


DIGIT: "0".."9"
HEXDIGIT: "a".."f"|"A".."F"|DIGIT
INT: DIGIT+
SIGNED_INT: ["+"|"-"] INT
DECIMAL: INT "." INT? | "." INT
_EXP: ("e"|"E") SIGNED_INT
FLOAT: INT _EXP | DECIMAL _EXP?
NUMBER: FLOAT | INT

WS: /[ \t\f\r\n]+/
%ignore WS
